//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otobusbiletrezervasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilce
    {
        public ilce()
        {
            this.TBLSEFERBILGIs = new HashSet<TBLSEFERBILGI>();
            this.TBLSEFERBILGIs1 = new HashSet<TBLSEFERBILGI>();
        }
    
        public int id { get; set; }
        public int il_id { get; set; }
        public string ad { get; set; }
    
        public virtual il il { get; set; }
        public virtual ICollection<TBLSEFERBILGI> TBLSEFERBILGIs { get; set; }
        public virtual ICollection<TBLSEFERBILGI> TBLSEFERBILGIs1 { get; set; }
    }
}
