//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otobusbiletrezervasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKAPTAN
    {
        public TBLKAPTAN()
        {
            this.TBLSEFERBILGIs = new HashSet<TBLSEFERBILGI>();
        }
    
        public string KAPTONNO { get; set; }
        public string KAPTANADSOYAD { get; set; }
        public string KAPTANTELEFON { get; set; }
    
        public virtual ICollection<TBLSEFERBILGI> TBLSEFERBILGIs { get; set; }
    }
}
