//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otobusbiletrezervasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSEFERDETAY
    {
        public int YOLCULUKID { get; set; }
        public Nullable<int> SEFERNO { get; set; }
        public string YOLCUTC { get; set; }
        public string KOLTUK { get; set; }
    
        public virtual TBLSEFERBILGI TBLSEFERBILGI { get; set; }
    }
}
