//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otobusbiletrezervasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSEFERBILGI
    {
        public TBLSEFERBILGI()
        {
            this.TBLSEFERDETAYs = new HashSet<TBLSEFERDETAY>();
        }
    
        public int SEFERNO { get; set; }
        public Nullable<int> KALKIS { get; set; }
        public Nullable<int> VARIS { get; set; }
        public string TARIH { get; set; }
        public string SAAT { get; set; }
        public string KAPTAN { get; set; }
        public Nullable<short> FIYAT { get; set; }
    
        public virtual il il { get; set; }
        public virtual il il1 { get; set; }
        public virtual ilce ilce { get; set; }
        public virtual ilce ilce1 { get; set; }
        public virtual ICollection<TBLSEFERDETAY> TBLSEFERDETAYs { get; set; }
        public virtual TBLKAPTAN TBLKAPTAN { get; set; }
    }
}
