//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANKAPROJESI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHAREKET
    {
        public int ID { get; set; }
        public Nullable<int> GONDEREN { get; set; }
        public Nullable<int> ALICI { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
    
        public virtual TBLKISILER TBLKISILER { get; set; }
        public virtual TBLKISILER TBLKISILER1 { get; set; }
    }
}
