//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANKAPROJESI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHESAP
    {
        public int HESAPNO { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
    
        public virtual TBLKISILER TBLKISILER { get; set; }
    }
}
