//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANKAPROJESI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKISILER
    {
        public TBLKISILER()
        {
            this.TBLHAREKET = new HashSet<TBLHAREKET>();
            this.TBLHAREKET1 = new HashSet<TBLHAREKET>();
        }
    
        public int HESAPNO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TC { get; set; }
        public string TELEFON { get; set; }
        public string SIFRE { get; set; }
    
        public virtual ICollection<TBLHAREKET> TBLHAREKET { get; set; }
        public virtual ICollection<TBLHAREKET> TBLHAREKET1 { get; set; }
        public virtual TBLHESAP TBLHESAP { get; set; }
    }
}
