//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TELEFONVEMAILUYGULAMASI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKISILER
    {
        public int ID { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string TELEFON { get; set; }
        public string MAİL { get; set; }
    }
}
