//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etut_Merkezi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBRAN
    {
        public TBLBRAN()
        {
            this.TBLETUTs = new HashSet<TBLETUT>();
            this.TBLOGRETMEN = new HashSet<TBLOGRETMan>();
        }
    
        public byte BRANSID { get; set; }
        public string BRANSAD { get; set; }
    
        public virtual ICollection<TBLETUT> TBLETUTs { get; set; }
        public virtual ICollection<TBLOGRETMan> TBLOGRETMEN { get; set; }
    }
}
