//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etut_Merkezi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLETUT
    {
        public int ID { get; set; }
        public Nullable<byte> DERSID { get; set; }
        public Nullable<byte> OGRETMENID { get; set; }
        public Nullable<short> OGRENCIID { get; set; }
        public string TARIH { get; set; }
        public string SAAT { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBLBRAN TBLBRAN { get; set; }
        public virtual TBLOGRENCI TBLOGRENCI { get; set; }
        public virtual TBLOGRETMan TBLOGRETMan { get; set; }
    }
}
