//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etut_Merkezi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOGRENCI
    {
        public TBLOGRENCI()
        {
            this.TBLETUTs = new HashSet<TBLETUT>();
        }
    
        public short OGRID { get; set; }
        public string FOTOGRAF { get; set; }
        public string SINIF { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public string OGRAD { get; set; }
        public string OGRSOYAD { get; set; }
    
        public virtual ICollection<TBLETUT> TBLETUTs { get; set; }
    }
}
