//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etut_Merkezi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOGRETMan
    {
        public TBLOGRETMan()
        {
            this.TBLETUTs = new HashSet<TBLETUT>();
        }
    
        public byte OGRTID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<byte> BRANS { get; set; }
    
        public virtual TBLBRAN TBLBRAN { get; set; }
        public virtual ICollection<TBLETUT> TBLETUTs { get; set; }
    }
}
