//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MALIYETLENDIRMESISTEMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMALZEMELER
    {
        public TBLMALZEMELER()
        {
            this.TBLURUNMALZEMEDETAYs = new HashSet<TBLURUNMALZEMEDETAY>();
        }
    
        public short ID { get; set; }
        public Nullable<decimal> STOK { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public string NOTLAR { get; set; }
        public string MALZEMEADI { get; set; }
    
        public virtual ICollection<TBLURUNMALZEMEDETAY> TBLURUNMALZEMEDETAYs { get; set; }
    }
}
