//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MALIYETLENDIRMESISTEMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNLER
    {
        public TBLURUNLER()
        {
            this.TBLURUNSATIS = new HashSet<TBLURUNSATIS>();
        }
    
        public byte ID { get; set; }
        public string AD { get; set; }
        public Nullable<decimal> MFIYAT { get; set; }
        public Nullable<decimal> SFIYAT { get; set; }
        public Nullable<short> STOK { get; set; }
        public Nullable<System.DateTime> URETIMTARIHI { get; set; }
        public Nullable<System.DateTime> SNTUKETIMTARIHI { get; set; }
    
        public virtual TBLURUNMALZEMEDETAY TBLURUNMALZEMEDETAY { get; set; }
        public virtual ICollection<TBLURUNSATIS> TBLURUNSATIS { get; set; }
    }
}
