//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MALIYETLENDIRMESISTEMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNSATIS
    {
        public int SATISID { get; set; }
        public string ALICIADSOYAD { get; set; }
        public string ALICITELEFON { get; set; }
        public string ALICIADRES { get; set; }
        public Nullable<byte> URUNID { get; set; }
        public Nullable<decimal> URUNFIYAT { get; set; }
        public Nullable<short> URUNADET { get; set; }
    
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
