//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MALIYETLENDIRMESISTEMI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNMALZEMEDETAY
    {
        public byte URUNID { get; set; }
        public Nullable<short> URUNMALZEME { get; set; }
        public Nullable<decimal> URUNMALMIKTAR { get; set; }
        public Nullable<decimal> URUNMALFIYAT { get; set; }
        public Nullable<byte> URUNADET { get; set; }
    
        public virtual TBLMALZEMELER TBLMALZEMELER { get; set; }
        public virtual TBLURUNLER TBLURUNLER { get; set; }
    }
}
